name: linux-binary

on:
  release:
    types: [published]

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22.2.x

      uses: actions/setup-node@v2
      with:
        node-version: 22.2.x

    - run: yarn install

    - run: yarn compile

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: exe-output/jsreport-linux.tar.gz
